
import random
class Agent(object):
    """Base class for all agents(algorithms)"""
    def __init__(self,n):
        if n<1 or type(n) is not int:
            raise ValueError("invalid bandit number {}".format(n))
        self.bandit_num=n
        self.reward_track=[]
        self.pull_history=[[]]*n
        self.recent_pull=None
    def play(self,pull_results):
        """decide which bandit to pull, then acquire result from the given list. The base agent always randomly choose one
        @parameter:
        pull_results - results generated by MultiArmedBandit.pull_all()
        """
        bandit_choice=random.choice(range(self.bandit_num))
        reward=pull_results[band_choice]
        self.recent_pull=(bandit_choice,reward)
        self.pull_history[bandit_choice].append(reward)
        if self.reward_track is []:
            self.reward_track.append(reward)
        else:
            self.reward_trac.append(reward+self.reward_track[-1])
            
            

